name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      LD_LIBRARY_PATH: /usr/local/lib
      RAMS_TEST_CBC: true
      RAMS_TEST_CLP: true
      RAMS_TEST_GLPK: true
      RAMS_TEST_SCIP: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.4'
        bundler-cache: true
    
    - name: Cache optimization solvers
      uses: actions/cache@v4
      with:
        path: |
          glpk-4.60
          scipoptsuite-3.2.1
        key: ${{ runner.os }}-solvers-v1
        restore-keys: |
          ${{ runner.os }}-solvers-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y coinor-cbc coinor-clp
    
    - name: Build and install GLPK
      run: |
        if [[ ! -e glpk-4.60 ]]; then
          wget http://ftp.gnu.org/gnu/glpk/glpk-4.60.tar.gz
          tar xvfz glpk-4.60.tar.gz
          cd glpk-4.60
          ./configure
          make
        fi
        cd glpk-4.60
        sudo make install
    
    - name: Build and install SCIP
      run: |
        if [[ ! -e scipoptsuite-3.2.1 ]]; then
          wget http://scip.zib.de/download/release/scipoptsuite-3.2.1.tgz
          tar xvfz scipoptsuite-3.2.1.tgz
          cd scipoptsuite-3.2.1
          make
        fi
        cd scipoptsuite-3.2.1
        sudo make install INSTALLDIR=../../../../usr/local
    
    - name: Run tests
      run: bundle exec rake test